### ISSUE TITLE
No Connection Found !

### ISSUE THREAD

**Issue by vikalp-tomer** [jgalat/remote-app#6]
Hello there, I installed the app from play store and as soon as I opened it, it is showing me "No connection found :( " and then a button below it saying "Setup Connection" and after clicking it, it is redirecting me to a "server name", "RPC URL",......... input boxes. I want to download my torrents using it. Nice project btw.

**Comment by jgalat** [comment]
Hi @vikalp-tomer, thanks for trying the app!

The app only allows you to connect to a remote torrent server and manage it from your phone. It doesn't have a server of its own, so it won't be able to download torrents to your phone. I'll think about adding a wiki section eventually to this repository with tutorials and stuff

**Comment by vikalp-tomer** [comment]
Ohh ! Now, I understand it. Thanks for replying. Are you also working on some other open source react-native project ?

**Comment by jgalat** [comment]
No problem!
I'm not currently working on any other react-native projects
